.SUFFIXES: .inc .f .F
#-----------------------------------------------------------------------
# Makefile for IBM RS6000
#-----------------------------------------------------------------------

# C-preprocessor
CPP     = /usr/ccs/lib/cpp -P -C   $*.F >$*.f
FC=xlf

CFLAGS = -O
FFLAGS = -O3 -qarch=auto
FREE   = -qfree=f90

DOBJ =  preclib.o timing.o derrf.o dclock.o  diolib.o dlexlib.o drdatab.o 

#-----------------------------------------------------------------------
# general rules
#-----------------------------------------------------------------------

libdmy.a: $(DOBJ) lapack_double.o linpack_double.o
	-rm libdmy.a
	ar vq libdmy.a $(DOBJ)

# files which do not require autodouble 
lapack_double.o: lapack_double.f
	$(FC) $(FFLAGS) $(NOFREE) -c lapack_double.f
lapack_single.o: lapack_single.f
	$(FC) $(FFLAGS) $(NOFREE) -c lapack_single.f
linpack_double.o: linpack_double.f
	$(FC) $(FFLAGS) $(NOFREE) -c linpack_double.f
linpack_single.o: linpack_single.f
	$(FC) $(FFLAGS) $(NOFREE) -c linpack_single.f


.c.o:
	$(CC) $(CFLAGS) -c $*.c
.F.o:
	$(CPP) 
	$(FC) $(FFLAGS) $(FREE) $(INCS) -c $*.f
.F.f:
	$(CPP) 
.f.o:
	$(FC) $(FFLAGS) $(FREE) $(INCS) -c $*.f
