.SUFFIXES: .inc .f90 .f .F
#-----------------------------------------------------------------------
# Makefile for HP
#-----------------------------------------------------------------------

# C-preprocessor
CPP	= +cpp=yes
FC	= f90
CC	= cc
AR	= ar
RM	= rm
LN	= ln

#PROF	= +pa
# compiler flags
CFLAGS	= +O2 +Odataprefetch $(PROF)
FFLAGS	= +O2 +Odataprefetch +Olibcalls +FPD $(PROF)

DOBJ =  preclib.o timing.o derrf.o dclock.o  diolib.o dlexlib.o drdatab.o

#-----------------------------------------------------------------------
# general rules
#-----------------------------------------------------------------------

libdmy.a: $(DOBJ) lapack_double.o linpack_double.o
	$(RM) -f libdmy.a
	$(AR) vq libdmy.a $(DOBJ)

# files which do not require autodouble 

.c.o:
	$(CC) $(CFLAGS) -c $*.c
.F.o:
	$(RM) -f $*.f90
	$(LN) $*.F $*.f90
	$(FC) $(CPP) $(FFLAGS) $(INCS) -c $*.f90
	$(RM) -f $*.f90
.f.o:
	$(FC) $(FFLAGS) $(INCS) -c $*.f
